import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const sourcePath = resolve(root, "src/theme/orc-tokens.json");
const targetPath = resolve(root, "src/styles/tokens.css");
const mode = process.argv[2] ?? "--check";

if (!["--check", "--write"].includes(mode) || process.argv.length > 3) {
  console.error("Usage: node scripts/sync-theme.mjs [--check|--write]");
  process.exitCode = 2;
} else {
  const palettes = JSON.parse(await readFile(sourcePath, "utf8"));
  validatePalettes(palettes);
  const desired = renderCss(palettes);
  const current = await readFile(targetPath, "utf8").catch((error) => {
    if (error?.code === "ENOENT") return "";
    throw error;
  });

  if (current === desired) {
    console.log("Theme CSS is synchronized.");
  } else if (mode === "--write") {
    await writeFile(targetPath, desired);
    console.log("Synchronized src/styles/tokens.css.");
  } else {
    console.error("src/styles/tokens.css has drifted. Run `npm run theme:write`.");
    process.exitCode = 1;
  }
}

function validatePalettes(palettes) {
  const expectedThemes = ["day", "night"];
  const expectedRoles = [
    "bg", "panel", "border", "text", "heading", "muted", "accent", "accent-soft",
    "chip", "code", "green", "yellow", "red", "purple", "cyan", "orange",
  ];

  if (JSON.stringify(Object.keys(palettes)) !== JSON.stringify(expectedThemes)) {
    throw new Error("Theme source must contain only ordered day and night palettes.");
  }
  for (const theme of expectedThemes) {
    if (JSON.stringify(Object.keys(palettes[theme])) !== JSON.stringify(expectedRoles)) {
      throw new Error(`${theme} must contain the canonical 16 ordered roles.`);
    }
    for (const [role, value] of Object.entries(palettes[theme])) {
      if (!/^#[0-9a-f]{6}$/.test(value)) {
        throw new Error(`${theme}.${role} must be a lowercase six-digit hex color.`);
      }
    }
  }
}

function renderCss({ day, night }) {
  return `/* Generated by scripts/sync-theme.mjs from src/theme/orc-tokens.json. */
:root {
  color-scheme: light dark;

  /* Orc day */
${renderPalette(day, "  ")}

  /* Surface-aware semantic derivations. */
${renderDayDerivations("  ")}
${renderSharedDerivations("  ")}

  /* Stable typography, layout, and focus tokens. */
  --orc-font-sans: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  --orc-font-mono: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  --orc-space-1: 4px;
  --orc-space-2: 8px;
  --orc-space-3: 12px;
  --orc-space-4: 16px;
  --orc-space-5: 24px;
  --orc-radius-sm: 4px;
  --orc-radius-md: 8px;
  --orc-radius-pill: 999px;
  --orc-focus-ring: 2px solid var(--orc-accent);
  --orc-focus-offset: 2px;
}

@media (prefers-color-scheme: dark) {
  :root {
    /* Orc night */
${renderPalette(night, "    ")}
${renderNightDerivations("    ")}
  }
}

:root[data-theme="dark"] {
  color-scheme: dark;
${renderPalette(night, "  ")}
${renderNightDerivations("  ")}
}

:root[data-theme="light"] {
  color-scheme: light;
${renderPalette(day, "  ")}
${renderDayDerivations("  ")}
}
`;
}

function renderPalette(palette, indent) {
  return Object.entries(palette)
    .map(([role, value]) => `${indent}--orc-${role}: ${value};`)
    .join("\n");
}

function renderDayDerivations(indent) {
  return `${indent}--orc-gate: color-mix(in srgb, var(--orc-orange) 60%, var(--orc-heading));
${indent}--orc-muted-strong: color-mix(in srgb, var(--orc-muted) 45%, var(--orc-heading));
${indent}--orc-accent-text: color-mix(in srgb, var(--orc-accent) 70%, var(--orc-heading));
${indent}--orc-red-text: color-mix(in srgb, var(--orc-red) 60%, var(--orc-heading));
${indent}--orc-yellow-text: color-mix(in srgb, var(--orc-yellow) 70%, var(--orc-heading));
${indent}--orc-green-text: color-mix(in srgb, var(--orc-green) 70%, var(--orc-heading));
${indent}--orc-purple-text: color-mix(in srgb, var(--orc-purple) 65%, var(--orc-heading));
${indent}--orc-accent-strong: color-mix(in srgb, var(--orc-accent) 70%, var(--orc-heading));`;
}

function renderNightDerivations(indent) {
  return `${indent}--orc-gate: var(--orc-orange);
${indent}--orc-muted-strong: color-mix(in srgb, var(--orc-muted) 45%, var(--orc-heading));
${indent}--orc-accent-text: var(--orc-accent);
${indent}--orc-red-text: var(--orc-red);
${indent}--orc-yellow-text: var(--orc-yellow);
${indent}--orc-green-text: var(--orc-green);
${indent}--orc-purple-text: var(--orc-purple);
${indent}--orc-accent-strong: var(--orc-accent);`;
}

function renderSharedDerivations(indent) {
  return `${indent}--orc-control-border: color-mix(in srgb, var(--orc-border) 65%, var(--orc-heading));
${indent}--orc-button-hover: color-mix(in srgb, var(--orc-accent) 10%, var(--orc-bg));
${indent}--orc-button-hover-chip: color-mix(in srgb, var(--orc-accent) 12%, var(--orc-chip));
${indent}--orc-button-hover-strong: color-mix(in srgb, var(--orc-accent-strong) 86%, var(--orc-heading));`;
}
